services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        MONGODB_URI: 'mongodb://mongo:27017/mydb'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
      - NEXT_PUBLIC_API_BASE_URL=http://next-app:3000
    restart: always
    depends_on:
      - mongo    
    ports:
      - 3000:3000
    networks:
      - my_network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - my_network 

volumes:
  mongo-data:

networks:
  my_network:
    external: true
